ALTER TABLE Client DROP COLUMN id;
ALTER TABLE Client ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE Credentials DROP COLUMN id;
ALTER TABLE Credentials ADD COLUMN id INT PRIMARY KEY REFERENCES Client(id);